### ISSUE TITLE
Problems with right-shift in Gear rollsum.

### ISSUE THREAD

**Issue by dbaarda** [tigerwill90/fastcdc#3]
This implementation copies another implementation that uses a right-shift in its Gear rollsum. This has problems I reported here;

https://github.com/ronomon/deduplication/issues/7

**Comment by tigerwill90** [comment]
I read your [recommendations](https://github.com/ronomon/deduplication/issues/8) as well as the very interesting [analysis](https://github.com/dbaarda/rollsum-chunking/blob/master/RESULTS.rst) you carried out. I will tests and benchmark your recommendations on optimal and speed chunking. Many thanks.
